example/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'', include(wagtail_urls)),
]

wagtailstreamforms/urls.py
from django.urls import path
from wagtailstreamforms import views
from wagtailstreamforms.utils.loading import get_advanced_settings_model

SettingsModel = get_advanced_settings_model()


urlpatterns = [
    path("<int:pk>/copy/", views.CopyFormView.as_view(), name="streamforms_copy"),
    path(
        "<int:pk>/submissions/",
        views.SubmissionListView.as_view(),
        name="streamforms_submissions",
    ),
    path(
        "<int:pk>/submissions/delete/",
        views.SubmissionDeleteView.as_view(),
        name="streamforms_delete_submissions",
    ),
]


if SettingsModel:  # pragma: no cover
    urlpatterns += [
        path(
            "<int:pk>/advanced/",
            views.AdvancedSettingsView.as_view(),
            name="streamforms_advanced",
        )
    ]

wagtailstreamforms/models/abstract.py
from django.db import models


class AbstractFormSetting(models.Model):
    form = models.OneToOneField(
        "wagtailstreamforms.Form",
        on_delete=models.CASCADE,
        related_name="advanced_settings",
    )

    class Meta:
        abstract = True

    def __str__(self):
        return self.form.title

wagtailstreamforms/models/file.py
from django.db import models, transaction
from django.db.models.signals import post_delete
from django.utils.translation import ugettext_lazy as _


class FormSubmissionFile(models.Model):
    """ Data for a form submission file. """

    submission = models.ForeignKey(
        "FormSubmission",
        verbose_name=_("Submission"),
        on_delete=models.CASCADE,
        related_name="files",
    )
    field = models.CharField(verbose_name=_("Field"), max_length=255)
    file = models.FileField(verbose_name=_("File"), upload_to="streamforms/")

    def __str__(self):
        return self.file.name

    class Meta:
        ordering = ["field", "file"]
        verbose_name = _("Form submission file")

    @property
    def url(self):
        return self.file.url


def delete_file_from_storage(instance, **kwargs):
    """ Cleanup deleted files from disk """
    transaction.on_commit(lambda: instance.file.delete(False))


post_delete.connect(delete_file_from_storage, sender=FormSubmissionFile)

wagtailstreamforms/models/submission.py
import json

from django.db import models
from django.utils.translation import ugettext_lazy as _


class FormSubmission(models.Model):
    """ Data for a form submission. """

    form_data = models.TextField(_("Form data"))
    form = models.ForeignKey("Form", verbose_name=_("Form"), on_delete=models.CASCADE)
    submit_time = models.DateTimeField(_("Submit time"), auto_now_add=True)

    def get_data(self):
        """ Returns dict with form data. """
        form_data = json.loads(self.form_data)

        form_data.update({"submit_time": self.submit_time})

        return form_data

    def __str__(self):
        return self.form_data

    class Meta:
        ordering = ["-submit_time"]
        verbose_name = _("Form submission")

wagtailstreamforms/forms.py
from collections import OrderedDict

from django import forms
from django.utils.translation import ugettext_lazy as _
from wagtailstreamforms.fields import get_fields
from wagtailstreamforms.utils.general import get_slug_from_string


class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("label_suffix", "")

        self.user = kwargs.pop("user", None)
        self.page = kwargs.pop("page", None)

        super().__init__(*args, **kwargs)


class FormBuilder:
    def __init__(self, fields):
        self.fields = fields

    @property
    def formfields(self):
        """ Return a list of form fields from the registered fields. """

        formfields = OrderedDict()

        registered_fields = get_fields()

        for field in self.fields:
            field_type = field.get("type")
            field_value = field.get("value")

            # check we have the field
            if field_type not in registered_fields:
                raise AttributeError(
                    "Could not find a registered field of type %s" % field_type
                )

            # check there is a label
            if "label" not in field_value:
                raise AttributeError(
                    "The block for %s must contain a label of type blocks.CharBlock(required=True)"
                    % field_type
                )

            # slugify the label for the field name
            field_name = get_slug_from_string(field_value.get("label"))

            # get the field
            registered_cls = registered_fields[field_type]()
            field_cls = registered_cls.get_formfield(field_value)
            formfields[field_name] = field_cls

        # add fields to uniquely identify the form
        formfields["form_id"] = forms.CharField(widget=forms.HiddenInput)
        formfields["form_reference"] = forms.CharField(widget=forms.HiddenInput)

        return formfields

    def get_form_class(self):
        return type(str("StreamformsForm"), (BaseForm,), self.formfields)


class SelectDateForm(forms.Form):
    date_from = forms.DateTimeField(
        required=False, widget=forms.DateInput(attrs={"placeholder": _("Date from")})
    )
    date_to = forms.DateTimeField(
        required=False, widget=forms.DateInput(attrs={"placeholder": _("Date to")})
    )

wagtailstreamforms/views/advanced_settings.py
from django import forms
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext as _
from django.views.generic import UpdateView
from wagtailstreamforms.models import Form
from wagtailstreamforms.utils.loading import get_advanced_settings_model
from wagtailstreamforms.wagtail_hooks import FormURLHelper

SettingsModel = get_advanced_settings_model()


class AdvancedSettingsForm(forms.ModelForm):
    class Meta:
        exclude = ("form",)
        model = SettingsModel


class AdvancedSettingsView(UpdateView):
    form_class = AdvancedSettingsForm
    model = SettingsModel
    template_name = "streamforms/advanced_settings.html"
    success_message = _("Form '%s' advanced settings updated.")

    @property
    def url_helper(self):
        return FormURLHelper(model=Form)

    def get_object(self, queryset=None):
        form_pk = self.kwargs.get("pk")
        form = get_object_or_404(Form, pk=form_pk)

        try:
            obj = self.model.objects.get(form=form)
        except self.model.DoesNotExist:
            obj = self.model(form=form)

        return obj

    def form_valid(self, form):
        response = super().form_valid(form)
        self.create_success_message()
        return response

    def create_success_message(self):
        success_message = self.success_message % self.object.form
        messages.success(self.request, success_message)

    def get_success_url(self):
        return self.url_helper.index_url

wagtailstreamforms/views/copy.py
from django import forms
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic.detail import (
    BaseDetailView,
    SingleObjectTemplateResponseMixin,
)
from wagtail.contrib.modeladmin.helpers import PermissionHelper
from wagtailstreamforms.models import Form
from wagtailstreamforms.wagtail_hooks import FormURLHelper


class CopyForm(forms.Form):
    title = forms.CharField(label=_("New title"))
    slug = forms.SlugField(label=_("New slug"))

    def clean_slug(self):
        slug = self.cleaned_data["slug"]
        if Form.objects.filter(slug=slug).exists():
            raise forms.ValidationError("This slug is already in use")
        return slug


class CopyFormView(SingleObjectTemplateResponseMixin, BaseDetailView):
    model = Form
    template_name = "streamforms/confirm_copy.html"
    success_message = _("Form '%s' copied to '%s'.")

    @property
    def permission_helper(self):
        return PermissionHelper(model=self.model)

    @property
    def url_helper(self):
        return FormURLHelper(model=self.model)

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.permission_helper.user_can_create(self.request.user):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj

    def copy(self, request, *args, **kwargs):
        form = CopyForm(request.POST)

        if form.is_valid():

            copied = self.object.copy()
            copied.title = form.cleaned_data["title"]
            copied.slug = form.cleaned_data["slug"]

            copied.save()

            self.create_success_message(copied)

            return HttpResponseRedirect(self.get_success_url())

        context = self.get_context_data(object=self.object)
        context["form"] = form

        return self.render_to_response(context)

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(object=self.object)
        context["form"] = CopyForm(
            initial={"title": self.object.title, "slug": self.object.slug}
        )

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return self.copy(request, *args, **kwargs)

    def create_success_message(self, copied):
        success_message = self.success_message % (self.object, copied)
        messages.success(self.request, success_message)

    def get_success_url(self):
        return self.url_helper.index_url

wagtailstreamforms/views/submission_delete.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.translation import ungettext
from django.views.generic import DeleteView
from wagtail.contrib.modeladmin.helpers import PermissionHelper
from wagtailstreamforms.models import Form


class SubmissionDeleteView(DeleteView):
    model = Form
    template_name = "streamforms/confirm_delete.html"

    @property
    def permission_helper(self):
        return PermissionHelper(model=self.model)

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.permission_helper.user_can_delete_obj(
            self.request.user, self.object
        ):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj

    def get_submissions(self):
        submission_ids = self.request.GET.getlist("selected-submissions")
        submission_class = self.object.get_submission_class()
        return submission_class._default_manager.filter(id__in=submission_ids)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["submissions"] = self.get_submissions()
        return context

    def delete(self, request, *args, **kwargs):
        success_url = self.get_success_url()
        submissions = self.get_submissions()
        count = submissions.count()
        submissions.delete()
        self.create_success_message(count)
        return HttpResponseRedirect(success_url)

    def create_success_message(self, count):
        messages.success(
            self.request,
            ungettext(
                "One submission has been deleted.",
                "%(count)d submissions have been deleted.",
                count,
            )
            % {"count": count},
        )

    def get_success_url(self):
        return reverse(
            "wagtailstreamforms:streamforms_submissions", kwargs={"pk": self.object.pk}
        )

wagtailstreamforms/views/submission_list.py
import csv
import datetime

from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpResponse
from django.utils.encoding import smart_str
from django.utils.translation import ugettext as _
from django.views.generic import ListView
from django.views.generic.detail import SingleObjectMixin
from wagtail.contrib.modeladmin.helpers import PermissionHelper
from wagtailstreamforms import hooks
from wagtailstreamforms.forms import SelectDateForm
from wagtailstreamforms.models import Form


class SubmissionListView(SingleObjectMixin, ListView):
    paginate_by = 25
    page_kwarg = "p"
    template_name = "streamforms/index_submissions.html"
    filter_form = None
    model = Form

    @property
    def permission_helper(self):
        return PermissionHelper(model=self.model)

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.permission_helper.user_can_list(self.request.user):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        pk = self.kwargs.get(self.pk_url_kwarg)
        try:
            qs = self.model.objects.all()
            for fn in hooks.get_hooks("construct_form_queryset"):
                qs = fn(qs, self.request)
            return qs.get(pk=pk)
        except self.model.DoesNotExist:
            raise Http404(_("No Form found matching the query"))

    def get(self, request, *args, **kwargs):
        self.filter_form = SelectDateForm(request.GET)

        if request.GET.get("action") == "CSV":
            return self.csv()

        return super().get(request, *args, **kwargs)

    def csv(self):
        queryset = self.get_queryset()
        data_fields = self.object.get_data_fields()
        data_headings = [smart_str(label) for name, label in data_fields]

        response = HttpResponse(content_type="text/csv; charset=utf-8")
        response["Content-Disposition"] = "attachment;filename=export.csv"

        writer = csv.writer(response)
        writer.writerow(data_headings)
        for s in queryset:
            data_row = []
            form_data = s.get_data()
            for name, label in data_fields:
                data_row.append(smart_str(form_data.get(name)))
            writer.writerow(data_row)

        return response

    def get_queryset(self):
        submission_class = self.object.get_submission_class()
        self.queryset = submission_class._default_manager.filter(form=self.object)

        # filter the queryset by the required dates
        if self.filter_form.is_valid():
            date_from = self.filter_form.cleaned_data.get("date_from")
            date_to = self.filter_form.cleaned_data.get("date_to")
            if date_from:
                self.queryset = self.queryset.filter(submit_time__gte=date_from)
            if date_to:
                date_to += datetime.timedelta(days=1)
                self.queryset = self.queryset.filter(submit_time__lte=date_to)

        return self.queryset.prefetch_related("files")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        data_fields = self.object.get_data_fields()
        data_headings = [label for name, label in data_fields]

        # populate data rows from paginator
        data_rows = []
        for s in context["page_obj"]:
            form_data = s.get_data()
            form_files = s.files.all()
            data_row = [form_data.get(name) for name, label in data_fields]
            data_rows.append(
                {"model_id": s.id, "fields": data_row, "files": form_files}
            )

        context.update(
            {
                "filter_form": self.filter_form,
                "data_rows": data_rows,
                "data_headings": data_headings,
                "has_delete_permission": self.permission_helper.user_can_delete_obj(
                    self.request.user, self.object
                ),
            }
        )

        return context

wagtailstreamforms/templates/streamforms/advanced_settings.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with form_title=object %}Advanced form settings for {{ form_title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Advanced form settings" as title_str %}
    {% include "wagtailadmin/shared/header.html" with title=title_str subtitle=object icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <form action="." method="POST" novalidate>
            {% csrf_token %}
            <ul class="fields">
                {% block visible_fields %}
                    {% for field in form.visible_fields %}
                        {% include "wagtailadmin/shared/field_as_li.html" %}
                    {% endfor %}
                {% endblock %}
                <li>
                    <input type="submit" value="{% trans 'Save' %}" class="button" />
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

wagtailstreamforms/templates/streamforms/confirm_copy.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with form_title=object.title|capfirst %}Copy of {{ form_title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Copy" as copy_str %}
    {% include "wagtailadmin/shared/header.html" with title=copy_str subtitle=object.title icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <p>{% trans 'Are you sure you want to copy this form?' %}</p>
        <form action="." method="POST" novalidate>
            {% csrf_token %}
            <ul class="fields">
                {% block visible_fields %}
                    {% for field in form.visible_fields %}
                        {% include "wagtailadmin/shared/field_as_li.html" %}
                    {% endfor %}
                {% endblock %}
                <li>
                    <input type="submit" value="{% trans 'Copy' %}" class="button" />
                </li>
            </ul>
        </form>
    </div>
{% endblock %}

wagtailstreamforms/templates/streamforms/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with form_title=object.title|capfirst %}Submissions of {{ form_title }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-explorer{% endblock %}

{% block content %}
    {% trans "Delete form data" as del_str %}
    {% include "wagtailadmin/shared/header.html" with title=del_str subtitle=object.title icon="doc-empty-inverse" %}

    <div class="nice-padding">
        <p>
            {% blocktrans count counter=submissions.count %}
                Are you sure you want to delete this form submission?
            {% plural %}
                Are you sure you want to delete these form submissions?
            {% endblocktrans %}
        </p>
        <form action="{% url 'wagtailstreamforms:streamforms_delete_submissions' object.id %}?{{ request.GET.urlencode }}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Delete' %}" class="button serious">
        </form>
    </div>
{% endblock %}

wagtailstreamforms/templates/streamforms/form_block.html
<h2>{{ value.form.title }}</h2>
<form{% if form.is_multipart %} enctype="multipart/form-data"{% endif %} action="{{ value.form_action }}" method="post" novalidate>
    {{ form.media }}
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
    {% for field in form.visible_fields %}
        {% include 'streamforms/partials/form_field.html' %}
    {% endfor %}
    <input type="submit" value="{{ value.form.submit_button_text }}">
</form>

wagtailstreamforms/templates/streamforms/index_submissions.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with form_title=object.title|capfirst %}Submissions of {{ form_title }}{% endblocktrans %}{% endblock %}
{% block extra_js %}
    {{ block.super }}
    {% include "streamforms/wagtailadmin/shared/datetimepicker_translations.html" %}

    <script>
        $(function() {
            $('#id_date_from').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });
            $('#id_date_to').datetimepicker({
                timepicker: false,
                format: 'Y-m-d',
            });
            var selectAllCheckbox = document.getElementById('select-all');
            var deleteButton = document.getElementById('delete-submissions');
            var selectedSubmissions = {};
            function updateActions() {
                var submissionCheckboxes = $('input[type=checkbox].select-submission');
                var someSubmissionsSelected = submissionCheckboxes.is(':checked');
                var everySubmissionSelected = !submissionCheckboxes.is(':not(:checked)');
                // Select all box state
                if (everySubmissionSelected) {
                    // Every submission has been selected
                    selectAllCheckbox.checked = true;
                    selectAllCheckbox.indeterminate = false;
                } else if (someSubmissionsSelected) {
                    // At least one, but not all submissions have been selected
                    selectAllCheckbox.checked = false;
                    selectAllCheckbox.indeterminate = true;
                } else {
                    // No submissions have been selected
                    selectAllCheckbox.checked = false;
                    selectAllCheckbox.indeterminate = false;
                }
                // Delete button state
                if (someSubmissionsSelected) {
                    deleteButton.classList.remove('disabled')
                    deleteButton.style.visibility = "visible";
                } else {
                    deleteButton.classList.add('disabled')
                    deleteButton.style.visibility = "hidden";
                }
            }
            // Event handlers
            $(selectAllCheckbox).on('change', function() {
                let checked = this.checked;
                // Update checkbox states
                $('input[type=checkbox].select-submission').each(function() {
                    this.checked = checked;
                });
                updateActions();
            });
            $('input[type=checkbox].select-submission').on('change', function() {
                updateActions();
            });
            // initial call to updateActions to bring delete button state in sync with checkboxes
            // in the case that some checkboxes are pre-checked (which will be the case in some
            // browsers when using the back button)
            $(document).ready(function() { updateActions() });
        });
    </script>
{% endblock %}
{% block content %}
    <header class="nice-padding hasform">
        <form action="" method="get" novalidate>
            <div class="row">
                <div class="left">
                    <div class="col">
                        <h1 class="icon icon-form">
                            {% blocktrans with form_title=object.title|capfirst %}Form data <span>{{ form_title }}</span>{% endblocktrans %}
                        </h1>
                    </div>
                    <div class="col search-bar">
                        <ul class="fields row rowflush">
                            {% for field in filter_form %}
                                {% include "wagtailadmin/shared/field_as_li.html" with field=field field_classes="field-small" li_classes="col4" %}
                            {% endfor %}
                            <li class="submit col2">
                                <button name="action" value="filter" class="button button-filter">{% trans 'Filter' %}</button>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="right">
                    <button name="action" value="CSV" class="button bicolor icon icon-download">{% trans 'Download CSV' %}</button>
                </div>
            </div>
        </form>
    </header>
    <div>
        {% if object_list %}
            <form action="{% url 'wagtailstreamforms:streamforms_delete_submissions' object.id %}" method="get">
                {% include "streamforms/list_submissions.html" %}
                {% include "streamforms/partials/pagination_nav.html" with items=page_obj %}
            </form>
        {% else %}
            <p class="no-results-message nice-padding">{% blocktrans with title=object.title %}There have been no submissions of the '{{ title }}' form.{% endblocktrans %}</p>
        {% endif %}
    </div>
{% endblock %}

wagtailstreamforms/templates/streamforms/list_submissions.html
{% load i18n %}
<div class="overflow">
<table class="listing">
    <col />
    <col />
    <col />
    <thead>
        {% if has_delete_permission %}
        <tr>
            <th colspan="{{ data_headings|length|add:1 }}">
                <button class="button no" id="delete-submissions" style="visibility: hidden">{% trans "Delete selected submissions" %}</button>
            </th>
        </tr>
        {% endif %}
        <tr>
            {% if has_delete_permission %}
                <th><input type="checkbox" id="select-all" /></th>
            {% endif %}
            {% for heading in data_headings %}
                <th>{{ heading }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for row in data_rows %}
            <tr>
                {% if has_delete_permission %}
                <td>
                    <input type="checkbox" name="selected-submissions" class="select-submission" value="{{ row.model_id }}" />
                </td>
                {% endif %}
                {% for cell in row.fields %}
                    <td>
                        {{ cell }}
                    </td>
                {% endfor %}
                <td>
            </tr>
            {% if row.files %}
            <tr>
                <td>{% trans 'Files' %}</td>
                <td colspan="{{ row.fields|length }}">
                    <ul>
                        {% for file in row.files %}
                        <li style="display: inline; margin-right: 20px;">
                            <a href="{{ file.url }}" target="_blank">{{ file }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
</table>
</div>

wagtailstreamforms/templates/streamforms/non_existent_form.html
{% load i18n %}
<p>{% trans 'Sorry, this form has been deleted.' %}</p>